import { createHmac } from 'node:crypto';
import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';
import type { CounterTicket, CounterPresence } from '../lib/counter/CounterTicketStore';
const state=vi.hoisted(()=>({tickets:[] as CounterTicket[],presence:{status:'available',since:'',reason:''} as CounterPresence,locked:false,manual:false,view:false}));
vi.mock('../lib/client/ClientAccountStore',()=>({getClientAccount:vi.fn(async(id:string)=>({customerId:id,organizationId:'org',status:'active',role:'seller',userCode:id==='nicolas'?'NR09':'MR07',sellerBranchAssignment:{primaryBranchId:'g01',allowedBranchIds:['g01']},sellerCounterSettings:{permissions:{manualTicketSelection:state.manual,viewFullQueue:state.view}}}))}));
vi.mock('../lib/client/CentralCustomerStore',()=>({getCentralCustomer:vi.fn(async()=>({firstName:'Nicolas',lastName:'Vendeur'}))}));
vi.mock('../lib/organization/OrganizationStore',()=>({allocateCounterTicketNumber:vi.fn(),getOrganization:vi.fn(async()=>({branches:[{branchId:'g01',branchCode:'G01',terminals:[]}]}))}));
vi.mock('../lib/counter/CounterTicketStore',async(importOriginal)=>{
 const original=await importOriginal<typeof import('../lib/counter/CounterTicketStore')>();
 return {...original,listCounterTickets:vi.fn(async()=>structuredClone(state.tickets)),getCounterPresence:vi.fn(async()=>({...state.presence})),acquireCounterAssignmentLock:vi.fn(async()=>{if(state.locked)return null;state.locked=true;return 'lock'}),releaseCounterAssignmentLock:vi.fn(async()=>{state.locked=false}),saveCounterTicketLocked:vi.fn(async(_org:string,_token:string,t:CounterTicket)=>{state.tickets=state.tickets.map(x=>x.id===t.id?structuredClone(t):x)}),saveCounterTicket:vi.fn(async(t:CounterTicket)=>{state.tickets.push(t)}),changeCounterPresence:vi.fn(async(_org:string,id:string,status:CounterPresence['status'],reason='')=>{if(state.locked)throw new Error('COUNTER_BUSY_RETRY');if(status!=='available'&&state.tickets.some(t=>t.sellerId===id&&['called','in-service'].includes(t.status)))throw new Error('ACTIVE_TICKET_BLOCKS_PRESENCE');state.presence={status,reason,since:new Date().toISOString()};return state.presence})};
});
import { GET, POST } from '../app/api/showroom/counter/route';
import { POST as presence } from '../app/api/comptoir/presence/route';
import { POST as logout } from '../app/api/auth/logout/route';
import { counterTicketCards } from '../lib/counter/CounterTicketPresentation';
function ticket(id:string,status:CounterTicket['status']='waiting',sellerId:string|null=null):CounterTicket{return {id,number:id,createdAt:new Date().toISOString(),calledAt:null,startedAt:null,completedAt:null,noShowAt:status==='no-show'?new Date().toISOString():null,status,sellerId,sellerName:null,storeId:'org',branchId:'g01',terminalId:'t1',customer:{id:'client',firstName:'Client',lastName:'Test',phone:'',email:''},vehicle:{id:'v1',brand:'',model:'',year:null,vin:null,engine:'',label:'Véhicule'},profile:'particulier',reason:'counter-request'};}
function req(body?:unknown,id='nicolas',role='seller'){const payload=Buffer.from(JSON.stringify({authenticated:true,channel:'counter',role,accessRole:role,permissions:[],customerId:id,organizationId:'org'})).toString('base64url');const cookie=`${payload}.${createHmac('sha256','test-secret').update(payload).digest('hex')}`;return new NextRequest('http://localhost/api/showroom/counter',{method:body?'POST':'GET',headers:{cookie:`tpa_session=${cookie}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
beforeEach(()=>{vi.stubEnv('TPA_SESSION_SECRET','test-secret');state.tickets=[];state.presence={status:'available',since:'',reason:''};state.locked=false;state.manual=false;state.view=false;});afterEach(()=>vi.unstubAllEnvs());
describe('Controlled counter integration',()=>{
 it('assigns the existing first waiting ticket and returns it immediately',async()=>{state.tickets=[ticket('A'),ticket('B')];const r=await (await GET(req())).json();expect(r.tickets.map((t:CounterTicket)=>t.id)).toEqual(['A']);expect(r.tickets[0]).toMatchObject({status:'called',sellerId:'nicolas'});expect(r.waitingCount).toBeNull();});
 it.each(['pause','mission'] as const)('does not assign while %s, resumes automatic assignment on return',async(status)=>{state.tickets=[ticket('A')];expect((await presence(req({status,reason:'Inventaire'}))).status).toBe(200);await GET(req());expect(state.tickets[0].status).toBe('waiting');await presence(req({status:'available'}));await GET(req());expect(state.tickets[0].sellerId).toBe('nicolas');});
 it.each(['called','in-service'] as const)('blocks pause, mission and logout with %s ticket',async(status)=>{state.tickets=[ticket('A',status,'nicolas')];for(const next of ['pause','mission'])expect((await presence(req({status:next}))).status).toBe(409);const result=await logout(req({}));expect(result.status).toBe(409);expect(result.headers.get('set-cookie')).toBeNull();expect(state.presence.status).toBe('available');});
 it('finishes then assigns the next ticket using existing transitions',async()=>{state.tickets=[ticket('A','called','nicolas'),ticket('B')];expect((await POST(req({action:'status',ticketId:'A',status:'in-service'}))).status).toBe(200);expect((await POST(req({action:'status',ticketId:'A',status:'completed'}))).status).toBe(200);await GET(req());expect(state.tickets[1]).toMatchObject({status:'called',sellerId:'nicolas'});});
 it('marks absent and resumes only when seller is free',async()=>{state.tickets=[ticket('A','called','nicolas')];await POST(req({action:'status',ticketId:'A',status:'no-show'}));expect(state.tickets[0].status).toBe('no-show');state.tickets.push(ticket('B','called','nicolas'));expect((await POST(req({action:'status',ticketId:'A',status:'called'}))).status).toBe(409);state.tickets.pop();expect((await POST(req({action:'status',ticketId:'A',status:'called'}))).status).toBe(200);});
 it('denies manual picking without permission',async()=>{state.tickets=[ticket('A')];expect((await POST(req({action:'status',ticketId:'A',status:'called'}))).status).toBe(403);expect(state.tickets[0].status).toBe('waiting');});
 it('keeps manual permission for authorized sellers',async()=>{state.manual=true;state.tickets=[ticket('A')];expect((await POST(req({action:'status',ticketId:'A',status:'called'}))).status).toBe(200);});
 it('does not expose or assign another organization or site',async()=>{state.tickets=[{...ticket('Other org'),storeId:'other'}, {...ticket('Other site'),branchId:'g02'}];const data=await (await GET(req())).json();expect(data.tickets).toEqual([]);expect((await POST(req({action:'status',ticketId:'Other org',status:'called'}))).status).toBe(403);});
 it('only reveals queue counts with viewFullQueue',async()=>{state.view=true;state.tickets=[ticket('A'),ticket('B'),ticket('C'),ticket('D')];const data=await (await GET(req())).json();expect(data.waitingCount).toBe(3);expect(counterTicketCards(data.tickets,'nicolas').cards).toHaveLength(1);});
 it('does not let another seller finish a ticket',async()=>{state.tickets=[ticket('A','in-service','nicolas')];expect((await POST(req({action:'status',ticketId:'A',status:'completed'},'youssef'))).status).toBe(409);});
 it('releases the real cookie after going offline and prevents subsequent assignment',async()=>{const r=await logout(req({}));expect(r.status).toBe(200);expect(r.headers.get('set-cookie')).toContain('Max-Age=0');expect(state.presence.status).toBe('offline');state.tickets=[ticket('A')];expect((await GET(req())).status).toBe(401);expect(state.tickets[0].status).toBe('waiting');});
 it('rejects unavailable assignment lock without mutation',async()=>{state.locked=true;state.tickets=[ticket('A')];expect((await GET(req())).status).toBe(503);expect((await presence(req({status:'pause'}))).status).toBe(503);expect(state.tickets[0].status).toBe('waiting');});
 it('rejects unauthenticated and non-seller requests',async()=>{expect((await GET(new NextRequest('http://localhost/api/showroom/counter'))).status).toBe(401);expect((await GET(req(undefined,'x','client'))).status).toBe(401);});
 it('caps cards at two and puts active ticket before no-shows',()=>{const list=[ticket('old','no-show','nicolas'),ticket('active','in-service','nicolas'),ticket('extra','no-show','nicolas'),ticket('other','called','youssef')];const result=counterTicketCards(list,'nicolas');expect(result.cards.map(t=>t.id)).toEqual(['active','old']);expect(result.additional).toBe(1);});
});
